export const AS = {
  EXIST: "exist",
  NOT_EXIST: "not.exist",
  BE_VISIBLE: "be.visible",
  NOT_BE_VISIBLE: "not.be.visible",
  BE_DISABLED: "be.disabled",
  NOT_BE_DISABLED: "not.be.disabled",
  BE_ENABLED: "be.enabled",
  NOT_BE_ENABLED: "not.be.enabled",
  HAVE_CLASS: "have.class",
  NOT_HAVE_CLASS: "not.have.class",
  HAVE_TEXT: "have.text",
  CONTAIN: "contain",
  NOT_CONTAIN: "not.contain",
  HAVE_VALUE: "have.value",
  NOT_HAVE_VALUE: "not.have.value",
  BE_CHECKED: "be.checked",
  NOT_BE_CHECKED: "not.be.checked",
  HAVE_LENGTH: "have.length",
  BE_EMPTY: "be.empty",
  NOT_BE_EMPTY: "not.be.empty",
  BE_FOCUSED: "be.focused",
  NOT_BE_FOCUSED: "not.be.focused",
  BE_SELECTED: "be.selected",
  NOT_BE_SELECTED: "not.be.selected",
  HAVE_ATTR: "have.attr",
  NOT_HAVE_ATTR: "not.have.attr",
} as const;
